

    [[redirects]]
  from = "/messages"
  to = "https://paretaserver.herokuapp.com/messages/"
  force = true
  status=200


   [[redirects]]
  from = "/events"
  to = "https://paretaserver.herokuapp.com/events/"
  force = true
  status=200


  [[redirects]]
  from = "/dashboard"
  to = "https://paretaserver.herokuapp.com/dashboard/"
  force = true
  status=200


  force = true
  status=200
  [[redirects]]
  from = "/articles/"
  to = "https://paretaserver.herokuapp.com/articles/"
  force = true
  status=200

 [[redirects]]
  from = "/register"
  to = "https://paretaserver.herokuapp.com/register/"
  force = true
  status=200

  [[redirects]]
  from = "/login"
  to = "https://paretaserver.herokuapp.com/login/"
  force = true
  status=200




[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
