

  [[redirects]]
  from = "/messages/*"
  to = "/messages"
  force = true
  status=200


   [[redirects]]
  from = "/events/*"
  to = "/events"
  force = true
  status=200


  [[redirects]]
  from = "/dashboard/*"
  to = "/dashboard"
  force = true
  status=200


  [[redirects]]
  from = "/articles/*"
  to = "/articles"
  force = true
  status=200

 [[redirects]]
  from = "/register/*"
  to = "/register"
  force = true
  status=200

  [[redirects]]
  from = "/login/*"
  to = "/login"
  force = true
  status=200




[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
