
  [[redirects]]
  from ="/login"
  to="https://paretaserver.herokuapp.com/login"
  status=200

  [[redirects]]
  from ="/register"
  to="https://paretaserver.herokuapp.com/register"
  status=200


 [[redirects]]
  from ="/events/events/:id"
  to="https://paretaserver.herokuapp.com/events/:id"
  status=200

 [[redirects]]
  from ="/events/subscribe"
  to="https://paretaserver.herokuapp.com/events/subscribe"
  status=200

 [[redirects]]
  from ="/events/search"
  to="https://paretaserver.herokuapp.com/events/search"
  status=200

 [[redirects]]
  from ="/events/:id"
  to="https://paretaserver.herokuapp.com/events/:id"
  status=200

  [[redirects]]
  from ="/events"
  to="https://paretaserver.herokuapp.com/events"
  status=200




  [[redirects]]
  from = "/articles/:id"
  to = "https://paretaserver.herokuapp.com/articles/:id"
  force = true
  status=200

  [[redirects]]
  from = "/articles/search"
  to = "https://paretaserver.herokuapp.com/articles/search"
  force = true
  status=200

  [[redirects]]
  from = "/articles/favorite"
  to = "https://paretaserver.herokuapp.com/articles/favorite"
  force = true
  status=200

  [[redirects]]
  from = "/articles"
  to = "https://paretaserver.herokuapp.com/articles/"
  force = true
  status=200

  [[redirects]]
  from = "/messages/received/:id"
  to = "https://paretaserver.herokuapp.com/messages/received/:id"
  force = true
  status=200

  [[redirects]]
  from = "/messages"
  to = "https://paretaserver.herokuapp.com/messages/"
  force = true
  status=200

 [[redirects]]
 from= "/events/dashboard/events/subscribed/:id"
 to="https://paretaserver.herokuapp.com/dashboard/events/subscribed/:id"
 status=200


 [[redirects]]
 from= "/dashboard/events/subscribed/"
 to="https://paretaserver.herokuapp.com/dashboard/events/subscribed/"
 status=200

 [[redirects]]
 from= "/events/dashboard/events/created/:id"
 to="https://paretaserver.herokuapp.com/dashboard/events/created/:id"
 status=200


 [[redirects]]
 from= "/dashboard/events/created/"
 to="https://paretaserver.herokuapp.com/dashboard/events/created/"
 status=200


  [[redirects]]
  from ="/dashboard"
  to="https://paretaserver.herokuapp.com/dashboard"
  status=200
